name: Lets run tests

on:
  push:
    branches: [master]  

jobs:
  test:
    name: Run Application tests
    runs-on: ubuntu-latest                        
    steps:
    - name: Checkout application code
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@master
      with:
        node-version: 18
        cashe: “npm"
    - name: Install dependencies    
      run: |
        cd lesson9/my-new-cypress-project/
        npm install
    - name: Run Cypress.io tests
      run: |
        cd lesson9/my-new-cypress-project/
        npx cypress run --spec "cypress/e2e/3-our-own-cases/finaltestcases.cy.js" --env "TASK_TITLE=Run final tests"
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: summary
        path: cypress/screenshots/
        retention-days: 30